// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7qFlKLG-a9eKJbjh7IEKp6az5an_c8lw',
    appId: '1:790326444118:web:807238168e00459fb0fbf7',
    messagingSenderId: '790326444118',
    projectId: 'selfreflectjournal-v1',
    authDomain: 'selfreflectjournal-v1.firebaseapp.com',
    storageBucket: 'selfreflectjournal-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3zdtkxdimmsc1-2ytbCxVwIYN5uKLJJs',
    appId: '1:790326444118:android:b230fe793d559c34b0fbf7',
    messagingSenderId: '790326444118',
    projectId: 'selfreflectjournal-v1',
    storageBucket: 'selfreflectjournal-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtSWkZXQaKdJTypU4J6rnrMt3PkFjtD_8',
    appId: '1:790326444118:ios:260013ff96dcb999b0fbf7',
    messagingSenderId: '790326444118',
    projectId: 'selfreflectjournal-v1',
    storageBucket: 'selfreflectjournal-v1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtSWkZXQaKdJTypU4J6rnrMt3PkFjtD_8',
    appId: '1:790326444118:ios:260013ff96dcb999b0fbf7',
    messagingSenderId: '790326444118',
    projectId: 'selfreflectjournal-v1',
    storageBucket: 'selfreflectjournal-v1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7qFlKLG-a9eKJbjh7IEKp6az5an_c8lw',
    appId: '1:790326444118:web:41c89a304beff849b0fbf7',
    messagingSenderId: '790326444118',
    projectId: 'selfreflectjournal-v1',
    authDomain: 'selfreflectjournal-v1.firebaseapp.com',
    storageBucket: 'selfreflectjournal-v1.firebasestorage.app',
  );

}